spring.application.name=Aimr
spring.profiles.active=dev,secrets
server.port=4000
spring.threads.virtual.enabled=true

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# MongoDB configuration
spring.mongodb.uri=mongodb://localhost:27017/${MONGO_DB_NAME}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
spring.datasource.username=${POSTGRES_USER_NAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Hikari pool configuration
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.pool-name=AimrHikariPool

#DDL configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

#Redis configuration
spring.data.redis.client-name=${REDIS_USER_NAME}
spring.data.redis.password=${REDIS_PASSWORD}

# Kafka Broker configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

#--------------Kafka topic configuration--------------------
#primary
kafka.ingest.topic=notification.ingest
kafka.audit.topic=notification.audit

#email
kafka.email.topic=notification.email
kafka.email.retry.topic=notification.email.retry
kafka.email.dlt.topic=notification.email.dlt
kafka.email.retry.group=email-retry-worker
kafka.email.dlt.group=email-dlt-worker

#push
kafka.push.topic=notification.push

#Sms
kafka.sms.topic=notification.sms

#Webhook
kafka.webhook.topic=notification.webhook
#--------------Kafka topic/group configuration--------------------

#Sendgrid api key
sendgrid.api-key=${SENDGRID_API_KEY}

#Jwt configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION_INTERVAL}

#Logging configuration
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.aimr.notify.security.filters.JwtAuthFilter=DEBUG
logging.level.com.aimr.notify.security.util.JwtUtil=DEBUG

# Enable Kafka Provider
messaging.providers.kafka.enabled=true
spring.kafka.listener.ack-mode=manual-immediate

# Aimr service rate limit configuration
aimr.notification.guard.dup-window-seconds=3600
aimr.notification.guard.channel-rate-limits.email=100
aimr.notification.guard.channel-rate-limits.sms=100
aimr.notification.guard.channel-rate-limits.push=100
aimr.notification.guard.channel-rate-limits.webhook=100
aimr.notification.guard.default-rate-limit=100


